export const GAME_SCHEDULE_LOADING = "GAME_SCHEDULE_LOADING";
export const GAME_SCHEDULE_LOADED = "GAME_SCHEDULE_LOADED";
export const GAME_SCHEDULE_ERRORS = "GAME_SCHEDULE_ERRORS";
export const GAME_DATA_LOADING = "GAME_DATA_LOADING";
export const GAME_DATA_LOADED = "GAME_DATA_LOADED";
export const GAME_DATA_ERRORS = "GAME_DATA_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
